linters:
  enable:
    # Default linters, plus these:
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gosec
    - misspell
    - paralleltest
    - revive

issues:
  exclude:
    # Disable scopelint errors on table driven tests
    - Using the variable on range scope `tc` in function literal
    # Disable documenting fstest Test functions
    - exported function Test\S* should have comment or be unexported
    - comment on exported function Test\S* should be of the form
  include:
    # Re-enable default excluded rules
    - EXC0001
    - EXC0002
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
