name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.16.x
    - name: Lint
      run: make lint

  test:
    strategy:
      matrix:
        platform: 
        - ubuntu-latest
        go:
        - 1.16.x
        - 1.17.x
        - 1.18.x
        - 1.19.x
        include:
        - platform: macos-latest
          go: 1.19.x
        - platform: windows-latest
          go: 1.19.x
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: make test
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERAGE_VERSION: 1.19
